[package]
name = "opencv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.63.0"
anyhow = "1.0.55"
dotenv = "0.15.0"
