[project]
name = "slack-notification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.0",
    "ruff>=0.11.11",
    "slack-bolt>=1.23.0",
    "ty>=0.0.1a6",
]
